//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace League_Analyser {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("League_Analyser.Resources.Localization.Messages.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Unexpected type:.
        /// </summary>
        public static string loadResources_unexpectedType {
            get {
                return ResourceManager.GetString("loadResources_unexpectedType", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Application version:.
        /// </summary>
        public static string mainWindow_appVersion {
            get {
                return ResourceManager.GetString("mainWindow_appVersion", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Currently downloading process is running, closing app may cause files corruption.
        ///Do you really want to close app now?.
        /// </summary>
        public static string mainWindow_closing_message {
            get {
                return ResourceManager.GetString("mainWindow_closing_message", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Confirm closing.
        /// </summary>
        public static string mainWindow_closing_title {
            get {
                return ResourceManager.GetString("mainWindow_closing_title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Data version:.
        /// </summary>
        public static string mainWindow_dataVersion {
            get {
                return ResourceManager.GetString("mainWindow_dataVersion", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Patch (DataDragon):.
        /// </summary>
        public static string mainWindow_patchVersion {
            get {
                return ResourceManager.GetString("mainWindow_patchVersion", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Your team:.
        /// </summary>
        public static string match_allayTeam {
            get {
                return ResourceManager.GetString("match_allayTeam", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Defeat.
        /// </summary>
        public static string match_defeat {
            get {
                return ResourceManager.GetString("match_defeat", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Returned empty championDataDto object.
        /// </summary>
        public static string match_emptyChampionData {
            get {
                return ResourceManager.GetString("match_emptyChampionData", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Enemy team:.
        /// </summary>
        public static string match_enemyTeam {
            get {
                return ResourceManager.GetString("match_enemyTeam", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Duration time.
        /// </summary>
        public static string match_gameDuration {
            get {
                return ResourceManager.GetString("match_gameDuration", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Match has been surrendered.
        /// </summary>
        public static string match_gameSurrendered {
            get {
                return ResourceManager.GetString("match_gameSurrendered", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu seconds.
        /// </summary>
        public static string match_popupSeconds {
            get {
                return ResourceManager.GetString("match_popupSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Achiever.
        /// </summary>
        public static string match_statisticBar_achiever {
            get {
                return ResourceManager.GetString("match_statisticBar_achiever", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Assist.
        /// </summary>
        public static string match_statisticBar_assist {
            get {
                return ResourceManager.GetString("match_statisticBar_assist", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Failed to load graphic.
        /// </summary>
        public static string match_unableToLoadImg {
            get {
                return ResourceManager.GetString("match_unableToLoadImg", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu (unknown champion).
        /// </summary>
        public static string match_unknownChampion {
            get {
                return ResourceManager.GetString("match_unknownChampion", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu (unknown map).
        /// </summary>
        public static string match_unknownMap {
            get {
                return ResourceManager.GetString("match_unknownMap", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Victory.
        /// </summary>
        public static string match_victory {
            get {
                return ResourceManager.GetString("match_victory", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Targets and achievements.
        /// </summary>
        public static string matchHistory_category_achievements {
            get {
                return ResourceManager.GetString("matchHistory_category_achievements", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Damage dealt.
        /// </summary>
        public static string matchHistory_category_damageDealt {
            get {
                return ResourceManager.GetString("matchHistory_category_damageDealt", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Damage received.
        /// </summary>
        public static string matchHistory_category_damageRecived {
            get {
                return ResourceManager.GetString("matchHistory_category_damageRecived", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Game time.
        /// </summary>
        public static string matchHistory_category_gameTime {
            get {
                return ResourceManager.GetString("matchHistory_category_gameTime", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu General statistics.
        /// </summary>
        public static string matchHistory_category_general {
            get {
                return ResourceManager.GetString("matchHistory_category_general", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Gold.
        /// </summary>
        public static string matchHistory_category_gold {
            get {
                return ResourceManager.GetString("matchHistory_category_gold", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Champion statistics.
        /// </summary>
        public static string matchHistory_category_playerStats {
            get {
                return ResourceManager.GetString("matchHistory_category_playerStats", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Used skills.
        /// </summary>
        public static string matchHistory_category_skills {
            get {
                return ResourceManager.GetString("matchHistory_category_skills", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu of.
        /// </summary>
        public static string matchHistory_scroll_rangeText {
            get {
                return ResourceManager.GetString("matchHistory_scroll_rangeText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Double kills.
        /// </summary>
        public static string matchHistory_statistic_achivements_double {
            get {
                return ResourceManager.GetString("matchHistory_statistic_achivements_double", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu First blood.
        /// </summary>
        public static string matchHistory_statistic_achivements_firstBlood {
            get {
                return ResourceManager.GetString("matchHistory_statistic_achivements_firstBlood", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu First turret.
        /// </summary>
        public static string matchHistory_statistic_achivements_firstTurret {
            get {
                return ResourceManager.GetString("matchHistory_statistic_achivements_firstTurret", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Participation in destroying inhibitors.
        /// </summary>
        public static string matchHistory_statistic_achivements_inhibitorParticipant {
            get {
                return ResourceManager.GetString("matchHistory_statistic_achivements_inhibitorParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Penta kills.
        /// </summary>
        public static string matchHistory_statistic_achivements_penta {
            get {
                return ResourceManager.GetString("matchHistory_statistic_achivements_penta", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Quadra kills.
        /// </summary>
        public static string matchHistory_statistic_achivements_quadra {
            get {
                return ResourceManager.GetString("matchHistory_statistic_achivements_quadra", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Largest killing spree.
        /// </summary>
        public static string matchHistory_statistic_achivements_seriesMax {
            get {
                return ResourceManager.GetString("matchHistory_statistic_achivements_seriesMax", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Targets stolen.
        /// </summary>
        public static string matchHistory_statistic_achivements_steals {
            get {
                return ResourceManager.GetString("matchHistory_statistic_achivements_steals", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Tripple kills.
        /// </summary>
        public static string matchHistory_statistic_achivements_tripple {
            get {
                return ResourceManager.GetString("matchHistory_statistic_achivements_tripple", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Participation in destroying turrers.
        /// </summary>
        public static string matchHistory_statistic_achivements_turretParticipant {
            get {
                return ResourceManager.GetString("matchHistory_statistic_achivements_turretParticipant", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Magic.
        /// </summary>
        public static string matchHistory_statistic_damage_magic {
            get {
                return ResourceManager.GetString("matchHistory_statistic_damage_magic", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu % magic.
        /// </summary>
        public static string matchHistory_statistic_damage_magicPercent {
            get {
                return ResourceManager.GetString("matchHistory_statistic_damage_magicPercent", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu To objectives.
        /// </summary>
        public static string matchHistory_statistic_damage_objectives {
            get {
                return ResourceManager.GetString("matchHistory_statistic_damage_objectives", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Physical.
        /// </summary>
        public static string matchHistory_statistic_damage_physical {
            get {
                return ResourceManager.GetString("matchHistory_statistic_damage_physical", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu % physical.
        /// </summary>
        public static string matchHistory_statistic_damage_physicalPercent {
            get {
                return ResourceManager.GetString("matchHistory_statistic_damage_physicalPercent", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu % team.
        /// </summary>
        public static string matchHistory_statistic_damage_teamPercent {
            get {
                return ResourceManager.GetString("matchHistory_statistic_damage_teamPercent", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Total.
        /// </summary>
        public static string matchHistory_statistic_damage_total {
            get {
                return ResourceManager.GetString("matchHistory_statistic_damage_total", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu True damage.
        /// </summary>
        public static string matchHistory_statistic_damage_true {
            get {
                return ResourceManager.GetString("matchHistory_statistic_damage_true", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu % true damage.
        /// </summary>
        public static string matchHistory_statistic_damage_truePercent {
            get {
                return ResourceManager.GetString("matchHistory_statistic_damage_truePercent", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Assists.
        /// </summary>
        public static string matchHistory_statistic_general_assists {
            get {
                return ResourceManager.GetString("matchHistory_statistic_general_assists", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Deaths.
        /// </summary>
        public static string matchHistory_statistic_general_deaths {
            get {
                return ResourceManager.GetString("matchHistory_statistic_general_deaths", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Kills.
        /// </summary>
        public static string matchHistory_statistic_general_kills {
            get {
                return ResourceManager.GetString("matchHistory_statistic_general_kills", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Minions killed.
        /// </summary>
        public static string matchHistory_statistic_general_minions {
            get {
                return ResourceManager.GetString("matchHistory_statistic_general_minions", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Gold gained.
        /// </summary>
        public static string matchHistory_statistic_gold_gained {
            get {
                return ResourceManager.GetString("matchHistory_statistic_gold_gained", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Gold ratio (spent/gained).
        /// </summary>
        public static string matchHistory_statistic_gold_ratio {
            get {
                return ResourceManager.GetString("matchHistory_statistic_gold_ratio", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Gold spent.
        /// </summary>
        public static string matchHistory_statistic_gold_spend {
            get {
                return ResourceManager.GetString("matchHistory_statistic_gold_spend", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Largest critical strike.
        /// </summary>
        public static string matchHistory_statistic_player_critMax {
            get {
                return ResourceManager.GetString("matchHistory_statistic_player_critMax", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Damage decreased by armor/magic resist.
        /// </summary>
        public static string matchHistory_statistic_player_damageMitigated {
            get {
                return ResourceManager.GetString("matchHistory_statistic_player_damageMitigated", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Damage decreased by shields.
        /// </summary>
        public static string matchHistory_statistic_player_damageShielded {
            get {
                return ResourceManager.GetString("matchHistory_statistic_player_damageShielded", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Health restored.
        /// </summary>
        public static string matchHistory_statistic_player_healthRestored {
            get {
                return ResourceManager.GetString("matchHistory_statistic_player_healthRestored", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Allays healed.
        /// </summary>
        public static string matchHistory_statistic_player_teammatesHealed {
            get {
                return ResourceManager.GetString("matchHistory_statistic_player_teammatesHealed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Vision score.
        /// </summary>
        public static string matchHistory_statistic_player_visionScore {
            get {
                return ResourceManager.GetString("matchHistory_statistic_player_visionScore", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wards placed.
        /// </summary>
        public static string matchHistory_statistic_player_wardsPlaced {
            get {
                return ResourceManager.GetString("matchHistory_statistic_player_wardsPlaced", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Usage of D.
        /// </summary>
        public static string matchHistory_statistic_skills_d {
            get {
                return ResourceManager.GetString("matchHistory_statistic_skills_d", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu % usage of D / % usage of F.
        /// </summary>
        public static string matchHistory_statistic_skills_dfRatio {
            get {
                return ResourceManager.GetString("matchHistory_statistic_skills_dfRatio", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Usage of E.
        /// </summary>
        public static string matchHistory_statistic_skills_e {
            get {
                return ResourceManager.GetString("matchHistory_statistic_skills_e", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu % usage of E.
        /// </summary>
        public static string matchHistory_statistic_skills_ePercent {
            get {
                return ResourceManager.GetString("matchHistory_statistic_skills_ePercent", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Usage of F.
        /// </summary>
        public static string matchHistory_statistic_skills_f {
            get {
                return ResourceManager.GetString("matchHistory_statistic_skills_f", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu &quot;F for Flash&quot; - player is retarded.
        /// </summary>
        public static string matchHistory_statistic_skills_fForFlash {
            get {
                return ResourceManager.GetString("matchHistory_statistic_skills_fForFlash", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Usage of Q.
        /// </summary>
        public static string matchHistory_statistic_skills_q {
            get {
                return ResourceManager.GetString("matchHistory_statistic_skills_q", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu % usage of Q.
        /// </summary>
        public static string matchHistory_statistic_skills_qPercent {
            get {
                return ResourceManager.GetString("matchHistory_statistic_skills_qPercent", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Total [Q, W, E, R].
        /// </summary>
        public static string matchHistory_statistic_skills_qwerTotal {
            get {
                return ResourceManager.GetString("matchHistory_statistic_skills_qwerTotal", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Usage of R.
        /// </summary>
        public static string matchHistory_statistic_skills_r {
            get {
                return ResourceManager.GetString("matchHistory_statistic_skills_r", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu % usage of R.
        /// </summary>
        public static string matchHistory_statistic_skills_rPercent {
            get {
                return ResourceManager.GetString("matchHistory_statistic_skills_rPercent", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Usage of W.
        /// </summary>
        public static string matchHistory_statistic_skills_w {
            get {
                return ResourceManager.GetString("matchHistory_statistic_skills_w", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu % usage of W.
        /// </summary>
        public static string matchHistory_statistic_skills_wPercent {
            get {
                return ResourceManager.GetString("matchHistory_statistic_skills_wPercent", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu % time being alive.
        /// </summary>
        public static string matchHistory_statistic_time_alive {
            get {
                return ResourceManager.GetString("matchHistory_statistic_time_alive", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Longest time being alive.
        /// </summary>
        public static string matchHistory_statistic_time_aliveMax {
            get {
                return ResourceManager.GetString("matchHistory_statistic_time_aliveMax", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Total time of dealt CC effects.
        /// </summary>
        public static string matchHistory_statistic_time_cc {
            get {
                return ResourceManager.GetString("matchHistory_statistic_time_cc", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Match history.
        /// </summary>
        public static string menu_matchHistory {
            get {
                return ResourceManager.GetString("menu_matchHistory", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Settings.
        /// </summary>
        public static string menu_settings {
            get {
                return ResourceManager.GetString("menu_settings", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Statistics.
        /// </summary>
        public static string menu_statistics {
            get {
                return ResourceManager.GetString("menu_statistics", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add new profile.
        /// </summary>
        public static string settings_addNewProfile {
            get {
                return ResourceManager.GetString("settings_addNewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Language.
        /// </summary>
        public static string settings_appLanguage {
            get {
                return ResourceManager.GetString("settings_appLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add profile.
        /// </summary>
        public static string settings_buttonAddNewProfile {
            get {
                return ResourceManager.GetString("settings_buttonAddNewProfile", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Save.
        /// </summary>
        public static string settings_buttonLanguageSave {
            get {
                return ResourceManager.GetString("settings_buttonLanguageSave", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Select.
        /// </summary>
        public static string settings_buttonProfileSelect {
            get {
                return ResourceManager.GetString("settings_buttonProfileSelect", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Update.
        /// </summary>
        public static string settings_buttonUpdate {
            get {
                return ResourceManager.GetString("settings_buttonUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Delete profile.
        /// </summary>
        public static string settings_delete {
            get {
                return ResourceManager.GetString("settings_delete", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Are you sure you want to delete this profile?.
        /// </summary>
        public static string settings_deleteProfile_message {
            get {
                return ResourceManager.GetString("settings_deleteProfile_message", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Delete profile.
        /// </summary>
        public static string settings_deleteProfile_title {
            get {
                return ResourceManager.GetString("settings_deleteProfile_title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Download from zero.
        /// </summary>
        public static string settings_downloadFromZero {
            get {
                return ResourceManager.GetString("settings_downloadFromZero", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Language will change after application reboot.
        /// </summary>
        public static string settings_languageRebootInfo {
            get {
                return ResourceManager.GetString("settings_languageRebootInfo", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Add.
        /// </summary>
        public static string settings_newPlayer_button_add {
            get {
                return ResourceManager.GetString("settings_newPlayer_button_add", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cancel.
        /// </summary>
        public static string settings_newPlayer_button_cancel {
            get {
                return ResourceManager.GetString("settings_newPlayer_button_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Username.
        /// </summary>
        public static string settings_newPlayer_name {
            get {
                return ResourceManager.GetString("settings_newPlayer_name", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Server.
        /// </summary>
        public static string settings_newPlayer_server {
            get {
                return ResourceManager.GetString("settings_newPlayer_server", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Tag.
        /// </summary>
        public static string settings_newPlayer_tag {
            get {
                return ResourceManager.GetString("settings_newPlayer_tag", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Unable to get DataDragon folder reference.
        /// </summary>
        public static string settings_noDDreference {
            get {
                return ResourceManager.GetString("settings_noDDreference", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Failed to get new version tag value.
        /// </summary>
        public static string settings_noUpdateLink {
            get {
                return ResourceManager.GetString("settings_noUpdateLink", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Data file version.
        /// </summary>
        public static string settings_profileDetails_dataVersion {
            get {
                return ResourceManager.GetString("settings_profileDetails_dataVersion", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Last game.
        /// </summary>
        public static string settings_profileDetails_lastGame {
            get {
                return ResourceManager.GetString("settings_profileDetails_lastGame", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Number of saved games.
        /// </summary>
        public static string settings_profileDetails_numberOfGames {
            get {
                return ResourceManager.GetString("settings_profileDetails_numberOfGames", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu (unknown).
        /// </summary>
        public static string settings_profileUnknown {
            get {
                return ResourceManager.GetString("settings_profileUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Resources.
        /// </summary>
        public static string settings_resourcesLanguage {
            get {
                return ResourceManager.GetString("settings_resourcesLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Select profile.
        /// </summary>
        public static string settings_selectProfile {
            get {
                return ResourceManager.GetString("settings_selectProfile", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Set as active.
        /// </summary>
        public static string settings_setActive {
            get {
                return ResourceManager.GetString("settings_setActive", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Settings.
        /// </summary>
        public static string settings_settingsText {
            get {
                return ResourceManager.GetString("settings_settingsText", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu New application version is avaiable.
        /// </summary>
        public static string settings_updateApp {
            get {
                return ResourceManager.GetString("settings_updateApp", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Closing application....
        /// </summary>
        public static string settings_updateBat_closing {
            get {
                return ResourceManager.GetString("settings_updateBat_closing", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Deleting update files....
        /// </summary>
        public static string settings_updateBat_deleting {
            get {
                return ResourceManager.GetString("settings_updateBat_deleting", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Preparing for installation....
        /// </summary>
        public static string settings_updateBat_preparing {
            get {
                return ResourceManager.GetString("settings_updateBat_preparing", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Starting new application&apos;s version....
        /// </summary>
        public static string settings_updateBat_starting {
            get {
                return ResourceManager.GetString("settings_updateBat_starting", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Copying files....
        /// </summary>
        public static string settings_updateBat_swapping {
            get {
                return ResourceManager.GetString("settings_updateBat_swapping", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu New resource files (DataDragon) are avaiable.
        /// </summary>
        public static string settings_updateDD {
            get {
                return ResourceManager.GetString("settings_updateDD", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu version.
        /// </summary>
        public static string settings_versionApp {
            get {
                return ResourceManager.GetString("settings_versionApp", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Atack.
        /// </summary>
        public static string timeline_attack_autoattack {
            get {
                return ResourceManager.GetString("timeline_attack_autoattack", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Minions.
        /// </summary>
        public static string timeline_attack_minion {
            get {
                return ResourceManager.GetString("timeline_attack_minion", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Monsters.
        /// </summary>
        public static string timeline_attack_monster {
            get {
                return ResourceManager.GetString("timeline_attack_monster", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Other.
        /// </summary>
        public static string timeline_attack_other {
            get {
                return ResourceManager.GetString("timeline_attack_other", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Turret.
        /// </summary>
        public static string timeline_attack_turret {
            get {
                return ResourceManager.GetString("timeline_attack_turret", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu assists.
        /// </summary>
        public static string timeline_axis_assists {
            get {
                return ResourceManager.GetString("timeline_axis_assists", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu deaths.
        /// </summary>
        public static string timeline_axis_deaths {
            get {
                return ResourceManager.GetString("timeline_axis_deaths", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu kills.
        /// </summary>
        public static string timeline_axis_kills {
            get {
                return ResourceManager.GetString("timeline_axis_kills", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu none.
        /// </summary>
        public static string timeline_axis_none {
            get {
                return ResourceManager.GetString("timeline_axis_none", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Selected {0} of {1} players.
        /// </summary>
        public static string timeline_axis_selectedPlayers {
            get {
                return ResourceManager.GetString("timeline_axis_selectedPlayers", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu By your team.
        /// </summary>
        public static string timeline_byAllayTeam {
            get {
                return ResourceManager.GetString("timeline_byAllayTeam", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu By enemy team.
        /// </summary>
        public static string timeline_byEnemyTeam {
            get {
                return ResourceManager.GetString("timeline_byEnemyTeam", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Participation in fight.
        /// </summary>
        public static string timeline_damageBar_participationInFight {
            get {
                return ResourceManager.GetString("timeline_damageBar_participationInFight", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu player.
        /// </summary>
        public static string timeline_damagebar_participationPlayer {
            get {
                return ResourceManager.GetString("timeline_damagebar_participationPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu damage.
        /// </summary>
        public static string timeline_damagebar_participationSkill {
            get {
                return ResourceManager.GetString("timeline_damagebar_participationSkill", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Player&apos;s participation.
        /// </summary>
        public static string timeline_damageSummary_playerParticipation {
            get {
                return ResourceManager.GetString("timeline_damageSummary_playerParticipation", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Allay Kill.
        /// </summary>
        public static string timeline_eventName_allayKill {
            get {
                return ResourceManager.GetString("timeline_eventName_allayKill", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Atakhan Kill.
        /// </summary>
        public static string timeline_eventName_atakhanKilled {
            get {
                return ResourceManager.GetString("timeline_eventName_atakhanKilled", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Baron Nashor Kill.
        /// </summary>
        public static string timeline_eventName_baronKilled {
            get {
                return ResourceManager.GetString("timeline_eventName_baronKilled", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Chemtech Dragon Kill.
        /// </summary>
        public static string timeline_eventName_dragonChemtechKilled {
            get {
                return ResourceManager.GetString("timeline_eventName_dragonChemtechKilled", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cloud Dragon Kill.
        /// </summary>
        public static string timeline_eventName_dragonCloudKilled {
            get {
                return ResourceManager.GetString("timeline_eventName_dragonCloudKilled", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Elder Dragon Kill.
        /// </summary>
        public static string timeline_eventName_dragonElderKilled {
            get {
                return ResourceManager.GetString("timeline_eventName_dragonElderKilled", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Hextech Dragon Kill.
        /// </summary>
        public static string timeline_eventName_dragonHextechKilled {
            get {
                return ResourceManager.GetString("timeline_eventName_dragonHextechKilled", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Infernal Dragon Kill.
        /// </summary>
        public static string timeline_eventName_dragonInfernalKilled {
            get {
                return ResourceManager.GetString("timeline_eventName_dragonInfernalKilled", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Mountain Dragon Kill.
        /// </summary>
        public static string timeline_eventName_dragonMountainKilled {
            get {
                return ResourceManager.GetString("timeline_eventName_dragonMountainKilled", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ocean Dragon Kill.
        /// </summary>
        public static string timeline_eventName_dragonOceanKilled {
            get {
                return ResourceManager.GetString("timeline_eventName_dragonOceanKilled", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Enemy Kill.
        /// </summary>
        public static string timeline_eventName_enemyKill {
            get {
                return ResourceManager.GetString("timeline_eventName_enemyKill", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Herald Kill.
        /// </summary>
        public static string timeline_eventName_heraldKilled {
            get {
                return ResourceManager.GetString("timeline_eventName_heraldKilled", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Inhibitor Destroyed.
        /// </summary>
        public static string timeline_eventName_inhibitorDestroyed {
            get {
                return ResourceManager.GetString("timeline_eventName_inhibitorDestroyed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Player Kill.
        /// </summary>
        public static string timeline_eventName_playerKill {
            get {
                return ResourceManager.GetString("timeline_eventName_playerKill", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Player Suicide.
        /// </summary>
        public static string timeline_eventName_suicideKill {
            get {
                return ResourceManager.GetString("timeline_eventName_suicideKill", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Turret Destroyed.
        /// </summary>
        public static string timeline_eventName_turretDestroyed {
            get {
                return ResourceManager.GetString("timeline_eventName_turretDestroyed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Voidgrub Kill.
        /// </summary>
        public static string timeline_eventName_voidgrubKilled {
            get {
                return ResourceManager.GetString("timeline_eventName_voidgrubKilled", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu In your team.
        /// </summary>
        public static string timeline_inAllayTeam {
            get {
                return ResourceManager.GetString("timeline_inAllayTeam", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu In enemy Team.
        /// </summary>
        public static string timeline_inEnemyTeam {
            get {
                return ResourceManager.GetString("timeline_inEnemyTeam", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu No information about event.
        /// </summary>
        public static string timeline_noEventTypeData {
            get {
                return ResourceManager.GetString("timeline_noEventTypeData", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Other sources.
        /// </summary>
        public static string timeline_other {
            get {
                return ResourceManager.GetString("timeline_other", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Damage.
        /// </summary>
        public static string timeline_popup_damage {
            get {
                return ResourceManager.GetString("timeline_popup_damage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Magic.
        /// </summary>
        public static string timeline_popup_damageMagic {
            get {
                return ResourceManager.GetString("timeline_popup_damageMagic", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Physical.
        /// </summary>
        public static string timeline_popup_damagePhysical {
            get {
                return ResourceManager.GetString("timeline_popup_damagePhysical", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Total.
        /// </summary>
        public static string timeline_popup_damageTotal {
            get {
                return ResourceManager.GetString("timeline_popup_damageTotal", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu True.
        /// </summary>
        public static string timeline_popup_damageTrue {
            get {
                return ResourceManager.GetString("timeline_popup_damageTrue", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Unknown player.
        /// </summary>
        public static string timeline_unknownPlayer {
            get {
                return ResourceManager.GetString("timeline_unknownPlayer", resourceCulture);
            }
        }
    }
}
