//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace League_Analyser {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Prompts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Prompts() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("League_Analyser.Resources.Localization.Prompts.Prompts", typeof(Prompts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu An error has occurred while connecting with API.
        /// </summary>
        internal static string api_error {
            get {
                return ResourceManager.GetString("api_error", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu A communal meeting is taking place around a bonfire in the server room, sausages provided by Riot Games.
        /// </summary>
        internal static string api_euneOnFire_msg {
            get {
                return ResourceManager.GetString("api_euneOnFire_msg", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu An error has occurred while connecting with API.
        /// </summary>
        internal static string api_euneOnFire_title {
            get {
                return ResourceManager.GetString("api_euneOnFire_title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Attempting to reconnect.
        /// </summary>
        internal static string api_reconnecting_msg {
            get {
                return ResourceManager.GetString("api_reconnecting_msg", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Donwloading data....
        /// </summary>
        internal static string api_reconnecting_title {
            get {
                return ResourceManager.GetString("api_reconnecting_title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Connection has timeouted.
        /// </summary>
        internal static string api_timeout_msg {
            get {
                return ResourceManager.GetString("api_timeout_msg", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu An error has occurred while connecting with API.
        /// </summary>
        internal static string api_timeout_title {
            get {
                return ResourceManager.GetString("api_timeout_title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu The program is awaiting for reconnection possibility.
        /// </summary>
        internal static string api_tooManyRequests_msg {
            get {
                return ResourceManager.GetString("api_tooManyRequests_msg", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu The server was overloaded due to too many requests.
        /// </summary>
        internal static string api_tooManyRequests_title {
            get {
                return ResourceManager.GetString("api_tooManyRequests_title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu An unexpected error has occurred with server connection.
        /// </summary>
        internal static string api_unexpectedError {
            get {
                return ResourceManager.GetString("api_unexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Waiting for recconect.
        /// </summary>
        internal static string api_waiting_msg {
            get {
                return ResourceManager.GetString("api_waiting_msg", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Downloading data....
        /// </summary>
        internal static string api_waiting_title {
            get {
                return ResourceManager.GetString("api_waiting_title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Failed to remove downloaded Data Dragon files.
        /// </summary>
        internal static string dd_deleteUpdateFilesError {
            get {
                return ResourceManager.GetString("dd_deleteUpdateFilesError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Downloading DataDragon files....
        /// </summary>
        internal static string dd_downloading {
            get {
                return ResourceManager.GetString("dd_downloading", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu DataDragon files update is avaibale.
        /// </summary>
        internal static string dd_hasUpdate {
            get {
                return ResourceManager.GetString("dd_hasUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Unable to find &quot;data&quot; folder.
        /// </summary>
        internal static string dd_noFolder {
            get {
                return ResourceManager.GetString("dd_noFolder", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Failed to check Data Dragon version.
        /// </summary>
        internal static string dd_noReference {
            get {
                return ResourceManager.GetString("dd_noReference", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Data Dragon reference does not exist.
        /// </summary>
        internal static string dd_notExist {
            get {
                return ResourceManager.GetString("dd_notExist", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Unable to check newest version of Data Dragon files.
        /// </summary>
        internal static string dd_noVersionReference {
            get {
                return ResourceManager.GetString("dd_noVersionReference", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Go to settings and perform DataDragon update.
        /// </summary>
        internal static string dd_update {
            get {
                return ResourceManager.GetString("dd_update", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Failed to download DataDragon files.
        /// </summary>
        internal static string dd_updateError {
            get {
                return ResourceManager.GetString("dd_updateError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Current version is {0}.
        /// </summary>
        internal static string dd_updateFinished_msg {
            get {
                return ResourceManager.GetString("dd_updateFinished_msg", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Successfully finished updating DataDragon process.
        /// </summary>
        internal static string dd_updateFinished_title {
            get {
                return ResourceManager.GetString("dd_updateFinished_title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu An error has occurred during DataDragon update process, reverting changes.
        /// </summary>
        internal static string dd_updateRevert {
            get {
                return ResourceManager.GetString("dd_updateRevert", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Failed to download data.
        /// </summary>
        internal static string load_downloadingError {
            get {
                return ResourceManager.GetString("load_downloadingError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Loading....
        /// </summary>
        internal static string load_loading {
            get {
                return ResourceManager.GetString("load_loading", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Failed to load data.
        /// </summary>
        internal static string load_loadingError {
            get {
                return ResourceManager.GetString("load_loadingError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Failed to deserialyze data.
        /// </summary>
        internal static string loadResources_deserialyze {
            get {
                return ResourceManager.GetString("loadResources_deserialyze", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Failed to load object data.
        /// </summary>
        internal static string loadResources_loadFile {
            get {
                return ResourceManager.GetString("loadResources_loadFile", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Failed to load image.
        /// </summary>
        internal static string loadResources_loadImage {
            get {
                return ResourceManager.GetString("loadResources_loadImage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Failed to save data to file.
        /// </summary>
        internal static string loadResources_saveFile {
            get {
                return ResourceManager.GetString("loadResources_saveFile", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Failed to serialyze data.
        /// </summary>
        internal static string loadResources_serialyze {
            get {
                return ResourceManager.GetString("loadResources_serialyze", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Failed to load whole data for {0} matches.
        /// </summary>
        internal static string match_dataAllNotLoaded {
            get {
                return ResourceManager.GetString("match_dataAllNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Data is up to date.
        /// </summary>
        internal static string match_dataUpToDate {
            get {
                return ResourceManager.GetString("match_dataUpToDate", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Unable to load details for this game.
        /// </summary>
        internal static string match_detailsNotLoaded {
            get {
                return ResourceManager.GetString("match_detailsNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Downloading match {0} of {1}.
        /// </summary>
        internal static string match_download {
            get {
                return ResourceManager.GetString("match_download", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Unable to download any game.
        /// </summary>
        internal static string match_downloadFailed {
            get {
                return ResourceManager.GetString("match_downloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu An error has occurred during downloading math data from zero.
        /// </summary>
        internal static string match_downloadFromZeroFailed {
            get {
                return ResourceManager.GetString("match_downloadFromZeroFailed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Downloading matches list.
        /// </summary>
        internal static string match_downloadingList {
            get {
                return ResourceManager.GetString("match_downloadingList", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Failed to download matches list.
        /// </summary>
        internal static string match_downloadListFailed {
            get {
                return ResourceManager.GetString("match_downloadListFailed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Returned empty object for this game.
        /// </summary>
        internal static string match_emptyTimeline {
            get {
                return ResourceManager.GetString("match_emptyTimeline", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Failed to load all graphics for {0} players.
        /// </summary>
        internal static string match_graphicAllNotLoaded {
            get {
                return ResourceManager.GetString("match_graphicAllNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Unable to locate file.
        /// </summary>
        internal static string match_graphicError_msg {
            get {
                return ResourceManager.GetString("match_graphicError_msg", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu An error has occurred during loading image.
        /// </summary>
        internal static string match_graphicError_title {
            get {
                return ResourceManager.GetString("match_graphicError_title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Unable to load all matches from server.
        /// </summary>
        internal static string match_notAllDownloaded {
            get {
                return ResourceManager.GetString("match_notAllDownloaded", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Unable to find data for this match.
        /// </summary>
        internal static string match_notFound {
            get {
                return ResourceManager.GetString("match_notFound", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Failed to load all statistics for {0} players.
        /// </summary>
        internal static string match_statAllNotLoaded {
            get {
                return ResourceManager.GetString("match_statAllNotLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Downloaded {0} new matches.
        /// </summary>
        internal static string match_updatedSucessfully_msg {
            get {
                return ResourceManager.GetString("match_updatedSucessfully_msg", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Successfully updated matches list.
        /// </summary>
        internal static string match_updatedSucessfully_title {
            get {
                return ResourceManager.GetString("match_updatedSucessfully_title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Successfully added new profile.
        /// </summary>
        internal static string profile_added {
            get {
                return ResourceManager.GetString("profile_added", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Successfully deleted profile.
        /// </summary>
        internal static string profile_deleted {
            get {
                return ResourceManager.GetString("profile_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Unable to delete profile.
        /// </summary>
        internal static string profile_deleteError {
            get {
                return ResourceManager.GetString("profile_deleteError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Unable to download player&apos;s data.
        /// </summary>
        internal static string profile_downloadError {
            get {
                return ResourceManager.GetString("profile_downloadError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu An error has occurred during downloading profiles list.
        /// </summary>
        internal static string profile_listError {
            get {
                return ResourceManager.GetString("profile_listError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Downloading player&apos;s data....
        /// </summary>
        internal static string profile_load {
            get {
                return ResourceManager.GetString("profile_load", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Welcome {0}!.
        /// </summary>
        internal static string profile_loadedSucessfully_msg {
            get {
                return ResourceManager.GetString("profile_loadedSucessfully_msg", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Successfully loaded player&apos;s profile.
        /// </summary>
        internal static string profile_loadedSucessfully_title {
            get {
                return ResourceManager.GetString("profile_loadedSucessfully_title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Unable to read player&apos;s data.
        /// </summary>
        internal static string profile_loadError {
            get {
                return ResourceManager.GetString("profile_loadError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Loading player&apos;s data....
        /// </summary>
        internal static string profile_loadingData {
            get {
                return ResourceManager.GetString("profile_loadingData", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu No reference to this user name.
        /// </summary>
        internal static string profile_noReference {
            get {
                return ResourceManager.GetString("profile_noReference", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Failed to add new profile.
        /// </summary>
        internal static string profile_notAdded {
            get {
                return ResourceManager.GetString("profile_notAdded", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Failed to read player&apos;s data.
        /// </summary>
        internal static string profile_notLoaded_msg {
            get {
                return ResourceManager.GetString("profile_notLoaded_msg", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu An error has occurred during reading player&apos;s data.
        /// </summary>
        internal static string profile_notLoaded_title {
            get {
                return ResourceManager.GetString("profile_notLoaded_title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Path {0} does not exist.
        /// </summary>
        internal static string profile_pathNotExist {
            get {
                return ResourceManager.GetString("profile_pathNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu An error has occurred during reading profile&apos;s data.
        /// </summary>
        internal static string profile_readError {
            get {
                return ResourceManager.GetString("profile_readError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Saving profile....
        /// </summary>
        internal static string profile_save {
            get {
                return ResourceManager.GetString("profile_save", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Failed to save profile.
        /// </summary>
        internal static string profile_saveError {
            get {
                return ResourceManager.GetString("profile_saveError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu You may now load profile data.
        /// </summary>
        internal static string profile_updatedSucessfully_msg {
            get {
                return ResourceManager.GetString("profile_updatedSucessfully_msg", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Successfully updated profile.
        /// </summary>
        internal static string profile_updatedSucessfully_title {
            get {
                return ResourceManager.GetString("profile_updatedSucessfully_title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Passed arguments does not match prompt&apos;s syntax {0}.
        /// </summary>
        internal static string prompt_argsInvalid_msg {
            get {
                return ResourceManager.GetString("prompt_argsInvalid_msg", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Failed to add prompt.
        /// </summary>
        internal static string prompt_argsInvalid_title {
            get {
                return ResourceManager.GetString("prompt_argsInvalid_title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Prompts list is empty.
        /// </summary>
        internal static string prompt_listEmpty_msg {
            get {
                return ResourceManager.GetString("prompt_listEmpty_msg", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Failed to update prompt.
        /// </summary>
        internal static string prompt_listEmpty_title {
            get {
                return ResourceManager.GetString("prompt_listEmpty_title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Downloading data....
        /// </summary>
        internal static string settings_downloading {
            get {
                return ResourceManager.GetString("settings_downloading", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Language change will apear after reboot.
        /// </summary>
        internal static string settings_languageSaved {
            get {
                return ResourceManager.GetString("settings_languageSaved", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Unable to read file.
        /// </summary>
        internal static string settings_loadFailed_msg {
            get {
                return ResourceManager.GetString("settings_loadFailed_msg", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Failed to load settings file.
        /// </summary>
        internal static string settings_loadFailed_title {
            get {
                return ResourceManager.GetString("settings_loadFailed_title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Reading data....
        /// </summary>
        internal static string settings_reading {
            get {
                return ResourceManager.GetString("settings_reading", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Settings have been saved.
        /// </summary>
        internal static string settings_saved {
            get {
                return ResourceManager.GetString("settings_saved", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Failed to save settings.
        /// </summary>
        internal static string settings_saveError_msg {
            get {
                return ResourceManager.GetString("settings_saveError_msg", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu An error has occurred during settings save process.
        /// </summary>
        internal static string settings_saveError_title {
            get {
                return ResourceManager.GetString("settings_saveError_title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Failed to check application update avability.
        /// </summary>
        internal static string update_checkFailed {
            get {
                return ResourceManager.GetString("update_checkFailed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Failed to remove downloaded update files.
        /// </summary>
        internal static string update_deleteUpdateFilesError {
            get {
                return ResourceManager.GetString("update_deleteUpdateFilesError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu An error has occurred during downloading application update.
        /// </summary>
        internal static string update_downloadFailed {
            get {
                return ResourceManager.GetString("update_downloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Downloading update files....
        /// </summary>
        internal static string update_downloading {
            get {
                return ResourceManager.GetString("update_downloading", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Downloaded {0}% ({1:0.0} from {2:0.0} kB).
        /// </summary>
        internal static string update_downloadProgressKb {
            get {
                return ResourceManager.GetString("update_downloadProgressKb", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Downloaded {0}% ({1:0.0} from {2:0.0} MB).
        /// </summary>
        internal static string update_downloadProgressMb {
            get {
                return ResourceManager.GetString("update_downloadProgressMb", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Finishing update process....
        /// </summary>
        internal static string update_finishing {
            get {
                return ResourceManager.GetString("update_finishing", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Initializing download....
        /// </summary>
        internal static string update_init {
            get {
                return ResourceManager.GetString("update_init", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Unable to create installer file.
        /// </summary>
        internal static string update_installerError_msg {
            get {
                return ResourceManager.GetString("update_installerError_msg", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Failed to update application.
        /// </summary>
        internal static string update_installerError_title {
            get {
                return ResourceManager.GetString("update_installerError_title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Go to settings and perform an update.
        /// </summary>
        internal static string update_isUpdate_msg {
            get {
                return ResourceManager.GetString("update_isUpdate_msg", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu An application update is avaiable.
        /// </summary>
        internal static string update_isUpdate_title {
            get {
                return ResourceManager.GetString("update_isUpdate_title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu The application will close in a moment and installation process will begin.
        /// </summary>
        internal static string update_rebootInfo {
            get {
                return ResourceManager.GetString("update_rebootInfo", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Unable to finish update process.
        /// </summary>
        internal static string update_saveError_msg {
            get {
                return ResourceManager.GetString("update_saveError_msg", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu An error has occurred during saving data.
        /// </summary>
        internal static string update_saveError_title {
            get {
                return ResourceManager.GetString("update_saveError_title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu An error has occurred during unzipping files process.
        /// </summary>
        internal static string update_unzipFailed {
            get {
                return ResourceManager.GetString("update_unzipFailed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Unzipping files (calculating size)....
        /// </summary>
        internal static string update_unzipInit {
            get {
                return ResourceManager.GetString("update_unzipInit", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Unzipped {0}% ({1:0.0} from {2:0.0} MB).
        /// </summary>
        internal static string update_unzipMb {
            get {
                return ResourceManager.GetString("update_unzipMb", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Updating application....
        /// </summary>
        internal static string update_updateProcess {
            get {
                return ResourceManager.GetString("update_updateProcess", resourceCulture);
            }
        }
    }
}
