//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace League_Analyser {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Prompts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Prompts() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("League_Analyser.Resources.Localization.Prompts.Prompts", typeof(Prompts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wystąpił błąd połączenia z API.
        /// </summary>
        internal static string api_error {
            get {
                return ResourceManager.GetString("api_error", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Trwa wspólne posiedzenie przy ognisku w serwerowni, kiełbaski zapewnione przez Riot Games.
        /// </summary>
        internal static string api_euneOnFire_msg {
            get {
                return ResourceManager.GetString("api_euneOnFire_msg", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wystąpił błąd połączenia z API.
        /// </summary>
        internal static string api_euneOnFire_title {
            get {
                return ResourceManager.GetString("api_euneOnFire_title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Próba ponownego połączenia.
        /// </summary>
        internal static string api_reconnecting_msg {
            get {
                return ResourceManager.GetString("api_reconnecting_msg", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Trwa pobieranie danych....
        /// </summary>
        internal static string api_reconnecting_title {
            get {
                return ResourceManager.GetString("api_reconnecting_title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Czas połączenia przekroczył żądany limit.
        /// </summary>
        internal static string api_timeout_msg {
            get {
                return ResourceManager.GetString("api_timeout_msg", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wystąpił błąd połączenia z API.
        /// </summary>
        internal static string api_timeout_title {
            get {
                return ResourceManager.GetString("api_timeout_title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Program oczekuje na ponowną możliwość połączenia.
        /// </summary>
        internal static string api_tooManyRequests_msg {
            get {
                return ResourceManager.GetString("api_tooManyRequests_msg", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nastąpiło przeciążenie serwera z powodu zbyt dużej liczby zapytań.
        /// </summary>
        internal static string api_tooManyRequests_title {
            get {
                return ResourceManager.GetString("api_tooManyRequests_title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wystąpił nieoczekiwany błąd przy próbie łączenia z serwerem.
        /// </summary>
        internal static string api_unexpectedError {
            get {
                return ResourceManager.GetString("api_unexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Oczekiwanie na ponowne połączenie.
        /// </summary>
        internal static string api_waiting_msg {
            get {
                return ResourceManager.GetString("api_waiting_msg", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Trwa pobieranie danych....
        /// </summary>
        internal static string api_waiting_title {
            get {
                return ResourceManager.GetString("api_waiting_title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wystąpił błąd deserializacji danych.
        /// </summary>
        internal static string loadResources_deserialyze {
            get {
                return ResourceManager.GetString("loadResources_deserialyze", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie udało się załadować danych obiektu.
        /// </summary>
        internal static string loadResources_loadFile {
            get {
                return ResourceManager.GetString("loadResources_loadFile", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie udało się odczytać grafiki.
        /// </summary>
        internal static string loadResources_loadImage {
            get {
                return ResourceManager.GetString("loadResources_loadImage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie udało się zapisać danych do pliku.
        /// </summary>
        internal static string loadResources_saveFile {
            get {
                return ResourceManager.GetString("loadResources_saveFile", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wystąpił błąd podczas serializacji danych.
        /// </summary>
        internal static string loadResources_serialyze {
            get {
                return ResourceManager.GetString("loadResources_serialyze", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Przekazane argumenty nie pasują do formatu komunikatu &quot;{0}&quot;.
        /// </summary>
        internal static string prompt_argsInvalid_msg {
            get {
                return ResourceManager.GetString("prompt_argsInvalid_msg", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wystąpił błąd poczas tworzenia powiadomienia.
        /// </summary>
        internal static string prompt_argsInvalid_title {
            get {
                return ResourceManager.GetString("prompt_argsInvalid_title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Lista powiadomień jest pusta.
        /// </summary>
        internal static string prompt_listEmpty_msg {
            get {
                return ResourceManager.GetString("prompt_listEmpty_msg", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wystąpił błąd poczas próby akualizacji powiadomienia.
        /// </summary>
        internal static string prompt_listEmpty_title {
            get {
                return ResourceManager.GetString("prompt_listEmpty_title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Trwa pobieranie danych....
        /// </summary>
        internal static string settings_downloading {
            get {
                return ResourceManager.GetString("settings_downloading", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zmiana wyświetlanego języka nastąpi po ponownym uruchomieniu aplikacji.
        /// </summary>
        internal static string settings_languageSaved {
            get {
                return ResourceManager.GetString("settings_languageSaved", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie udało się odczytać pliku.
        /// </summary>
        internal static string settings_loadFailed_msg {
            get {
                return ResourceManager.GetString("settings_loadFailed_msg", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wystąpił błąd podczas próby załadowania ustawień.
        /// </summary>
        internal static string settings_loadFailed_title {
            get {
                return ResourceManager.GetString("settings_loadFailed_title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pomyślnie dodano nowy profil.
        /// </summary>
        internal static string settings_profileAdded {
            get {
                return ResourceManager.GetString("settings_profileAdded", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pomyślnie usunięto profil.
        /// </summary>
        internal static string settings_profileDeleted {
            get {
                return ResourceManager.GetString("settings_profileDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie udało się usunąć profilu.
        /// </summary>
        internal static string settings_profileDeleteError {
            get {
                return ResourceManager.GetString("settings_profileDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Witaj, {0}!.
        /// </summary>
        internal static string settings_profileLoadedSucessfully_msg {
            get {
                return ResourceManager.GetString("settings_profileLoadedSucessfully_msg", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pomyślnie załadowano profil gracza.
        /// </summary>
        internal static string settings_profileLoadedSucessfully_title {
            get {
                return ResourceManager.GetString("settings_profileLoadedSucessfully_title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Brak danych odnośnie nazwy użytkownika.
        /// </summary>
        internal static string settings_profileNoReference {
            get {
                return ResourceManager.GetString("settings_profileNoReference", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie udało się dodać nowego profilu.
        /// </summary>
        internal static string settings_profileNotAdded {
            get {
                return ResourceManager.GetString("settings_profileNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie udało się odczytać danych gracza.
        /// </summary>
        internal static string settings_profileNotLoaded_msg {
            get {
                return ResourceManager.GetString("settings_profileNotLoaded_msg", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wystąpił błąd podczas odczytywannia danych.
        /// </summary>
        internal static string settings_profileNotLoaded_title {
            get {
                return ResourceManager.GetString("settings_profileNotLoaded_title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Ścieżka {0} nie istnieje.
        /// </summary>
        internal static string settings_profilePathNotExist {
            get {
                return ResourceManager.GetString("settings_profilePathNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wystąpił błąd podczas pobierania listy profili.
        /// </summary>
        internal static string settings_profilesListError {
            get {
                return ResourceManager.GetString("settings_profilesListError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Trwa odczytwanie danych....
        /// </summary>
        internal static string settings_reading {
            get {
                return ResourceManager.GetString("settings_reading", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wystąpił błąd odczytu pliku profilu.
        /// </summary>
        internal static string settings_readProfileError {
            get {
                return ResourceManager.GetString("settings_readProfileError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Zapisano ustawienia.
        /// </summary>
        internal static string settings_saved {
            get {
                return ResourceManager.GetString("settings_saved", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nie udało się zapisać pliku.
        /// </summary>
        internal static string settings_saveError_msg {
            get {
                return ResourceManager.GetString("settings_saveError_msg", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Wystąpił błąd podczas próby zapisania ustawiń.
        /// </summary>
        internal static string settings_saveError_title {
            get {
                return ResourceManager.GetString("settings_saveError_title", resourceCulture);
            }
        }
    }
}
